### ISSUE TITLE
Issue3: Uploadfehler

### ISSUE THREAD

**Issue by MrHaython** [MrHaython/Uploadmanager#3]
Der Uploadscript funktioniert nicht ganz richtig, bzw. wirft einen Fehler raus. Sollte gefixt werden.

Zu bearbeitende Datei: `dashboard.overview.php`

Dabei wird ein Fehler ausgeworfen, wenn man eine Datei versucht hochzuladen.

**Comment by ThomasRief** [comment]
ist erledigt
Ri
