### ISSUE TITLE
Issue8: Adminfunktion - Nutzerliste

### ISSUE THREAD

**Issue by MrHaython** [MrHaython/Uploadmanager#8]
Die Datei `dashboard.userlist.php` besitzt zur Zeit keine Funktion. Folgendes ist vorgesehen:

- [x] Anzeige einer Nutzerliste mit folgenden Spalten:
 - Nutzer-ID
 - Nutzername
 - Nutzerrechte
- [ ] Bearbeitungslink für jeden Nutzer um folgendes zu ändern:
 - Passwort ( nur auf Anfrage )
  - Als Vorbereitung für #7 sollte dem Admin - wenn der Nutzer eine Passwortzurücksetzung angefordert wurde - ein Link mit "Passwort ändern" angezeigt werden 
  - per GET wird ID des Nutzers mitgegeben
  - Das Script ersetzt das Passwort durch ein zufällig generiertes und teilt dies dem Admin mit, der dieses an den Nutzer weitergeben kann.
 - Rechte ( Angezeigt werden nur folgende Rechtegruppen: user, admin )

Außerdem wäre ein Headerlink zur 'dashboard.addUser.php` Datei recht praktisch.

**Comment by oreoPanda** [comment]
Ich werde mich um Passwortänderungen auf der Nutzerliste kümmern.
   - Eine neue Spalte in der Tabelle, in der ein Knopf "Passwort ändern" ist
   - Oberhalb der Nutzerliste wird nach Knopfdruck und neuladen der Seite eine extra Box erscheinen, in der das Passwort geändert werden kann.

**Comment by MrHaython** [comment]
Wie heute erklärt:

Greife in die Tabellengeneration der Seite ein und lass eine neue Spalte unter der des Nutzers erstellen, bei dem Du gerade das Passwort ändern möchtest. Am besten du gibst der Spalte des Nutzers noch extra eine ID per 
``` HTML
<tr id="id"></tr>
``` 
Dann kannst du beim Neuladen der Seite "url#id" mitgeben - als Lesezeichen. 

Folgendes sollte die Funktion können:
- [ ] Es lässt sich ein Passwort eingeben und ändern
- [ ] Es gibt eine "Random"-Funktion, mit der man das Passwort zufällig generieren kann. Dies wird automatisch in das Passwort-Feld eingefügt und man muss nur noch bestätigen.

Ich würde dir in etwa so was vorschlagen
```HTML
<tr>
    <td collspan="4">
        <form action method="POST">
            <input type="password" name="password" placeholder="Neues Passwort" />
            <input type="submit" name="submit" value="Ändern" />
            <p>
                <a> Passwort zufällig generieren </a>
            </p>
        </form>
    </td>
</tr>
```

**Comment by oreoPanda** [comment]
Sooo fertig, bis auf die Rechteveränderung. Brauchen wir die wirklich?
